# Comprehensive Offline Interview Question Bank
# 120+ questions across 10 categories

QUESTIONS_BANK = {
    'python': [
        'What is the difference between a list and a tuple in Python?',
        'Explain the concept of decorators in Python.',
        'What are list comprehensions? Provide an example.',
        'What is the difference between `*args` and `**kwargs`?',
        'Explain the Global Interpreter Lock (GIL) in Python.',
        'What is a generator in Python? How is it different from a list?',
        'Explain the concept of inheritance in Python. What are the types?',
        'What is a lambda function? When would you use it?',
        'Explain the difference between `is` and `==` in Python.',
        'What are context managers in Python? Can you provide an example?',
        'How does Python handle memory management?',
        'What is the difference between shallow copy and deep copy?',
        'Explain the MRO (Method Resolution Order) in Python.',
        'What are properties and descriptors in Python?',
        'How do you implement error handling in Python?',
        'What is a metaclass in Python?',
        'Explain iterators and the iterator protocol in Python.',
        'What is the difference between a class method and a static method?',
        'How do you implement polymorphism in Python?',
        'What is the `__init__` method used for in Python classes?',
    ],
    'django': [
        'What is the Django ORM and how does it work?',
        'Explain the Django project structure and its components.',
        'What is middleware in Django? Provide an example.',
        'How do you create and apply database migrations in Django?',
        'Explain Django QuerySets and how to filter them.',
        'What is the difference between `filter()` and `get()` in Django ORM?',
        'How do you implement authentication in Django?',
        'What are Django signals and when would you use them?',
        'Explain the Django template language and template inheritance.',
        'How do you implement permissions and groups in Django?',
        'What is Django REST Framework and how do you use it?',
        'Explain Django serializers and their purpose.',
        'How do you implement pagination in Django REST Framework?',
        'What is the purpose of Django forms?',
        'How do you handle file uploads in Django?',
        'Explain the Django admin interface and its customization.',
        'What is the difference between a ClassBasedView and FunctionBasedView?',
        'How do you implement caching in Django?',
        'What are Django view decorators? Provide examples.',
        'How do you handle errors and exceptions in Django views?',
    ],
    'react': [
        'What is React and why is it used?',
        'Explain the difference between functional and class components in React.',
        'What is JSX? How is it different from HTML?',
        'Explain state and props in React.',
        'What is the difference between state and props?',
        'Explain the React lifecycle methods (for class components).',
        'What are React Hooks? Provide examples of common hooks.',
        'What is the useState hook and how do you use it?',
        'Explain the useEffect hook in React.',
        'What is the useContext hook used for?',
        'How do you handle forms in React?',
        'Explain controlled vs uncontrolled components in React.',
        'What is the purpose of the key prop in React lists?',
        'How do you optimize React component performance?',
        'What is React Router and how do you use it?',
        'Explain Redux and state management in React applications.',
        'What is the purpose of middleware in Redux?',
        'How do you handle API calls in React?',
        'What are higher-order components (HOC) in React?',
        'Explain the concept of render props in React.',
    ],
    'javascript': [
        'What is the difference between var, let, and const in JavaScript?',
        'Explain closures in JavaScript.',
        'What is the difference between synchronous and asynchronous JavaScript?',
        'Explain callbacks, promises, and async/await.',
        'What is event delegation in JavaScript?',
        'Explain the event loop in JavaScript.',
        'What is the this keyword in JavaScript? How does it work?',
        'Explain prototypal inheritance in JavaScript.',
        'What is the difference between shallow and deep equality in JavaScript?',
        'How do you handle errors in JavaScript?',
        'What are array methods like map, filter, and reduce?',
        'Explain the spread operator (...) in JavaScript.',
        'What is destructuring in JavaScript?',
        'How do you implement debouncing and throttling in JavaScript?',
        'What is the difference between == and === in JavaScript?',
        'Explain template literals in JavaScript.',
        'What are arrow functions and how are they different from regular functions?',
        'How do you work with JSON in JavaScript?',
        'Explain the fetch API and how to make HTTP requests.',
        'What is the DOM and how do you manipulate it with JavaScript?',
    ],
    'mongodb': [
        'What is MongoDB and how is it different from SQL databases?',
        'Explain the document structure in MongoDB.',
        'What is a collection in MongoDB?',
        'How do you create a database and collection in MongoDB?',
        'Explain MongoDB query operators.',
        'What are aggregation pipelines in MongoDB?',
        'How do you implement indexing in MongoDB?',
        'What is the difference between insert, insertOne, and insertMany?',
        'How do you update documents in MongoDB?',
        'Explain the find() method in MongoDB.',
        'What are MongoDB transactions?',
        'How do you implement relationships in MongoDB?',
        'What is embedding vs referencing in MongoDB?',
        'Explain the MongoDB replica set.',
        'What is sharding in MongoDB?',
        'How do you implement validation in MongoDB?',
        'What are MongoDB indexes and how do they improve performance?',
        'Explain the $lookup operator in MongoDB aggregation.',
        'How do you handle large datasets in MongoDB?',
        'What is the difference between MongoDB and Firebase?',
    ],
    'sql': [
        'What is a database and what are its advantages?',
        'Explain relational databases and the concept of normalization.',
        'What are the different types of SQL joins?',
        'Explain the difference between INNER, LEFT, RIGHT, and FULL joins.',
        'What are indexes and how do they improve query performance?',
        'Explain SQL transactions and ACID properties.',
        'What is the difference between DELETE, DROP, and TRUNCATE?',
        'How do you implement relationships between tables in SQL?',
        'What are foreign keys and primary keys?',
        'Explain GROUP BY and HAVING clauses in SQL.',
        'What are subqueries and correlated subqueries?',
        'How do you use aggregate functions in SQL?',
        'Explain window functions in SQL.',
        'What is the difference between UNION and UNION ALL?',
        'How do you optimize SQL queries?',
        'What are stored procedures and triggers in SQL?',
        'Explain the concept of views in SQL.',
        'What are constraints in SQL databases?',
        'How do you handle NULL values in SQL?',
        'What is query optimization and execution plans?',
    ],
    'java': [
        'What is Java and why is it widely used?',
        'Explain the difference between JDK, JRE, and JVM.',
        'What are the principles of object-oriented programming?',
        'Explain inheritance and polymorphism in Java.',
        'What is encapsulation in Java?',
        'Explain abstraction in Java.',
        'What is the difference between an abstract class and an interface?',
        'What are access modifiers in Java?',
        'Explain collections in Java (List, Set, Map).',
        'What is the difference between ArrayList and LinkedList?',
        'Explain exception handling in Java.',
        'What are checked and unchecked exceptions in Java?',
        'Explain the concept of multithreading in Java.',
        'What is synchronization in Java?',
        'Explain the Java memory model and garbage collection.',
        'What are generics in Java?',
        'Explain lambda expressions in Java.',
        'What is the Java Stream API?',
        'Explain the difference between static and non-static members in Java.',
        'What are inner classes in Java?',
    ],
    'html_css': [
        'What is HTML and what are its basic elements?',
        'Explain the semantic elements in HTML5.',
        'What are HTML forms and their elements?',
        'Explain the difference between block and inline elements.',
        'What is CSS and how do you use it?',
        'Explain CSS selectors (element, class, ID, attribute).',
        'What is the CSS box model?',
        'Explain CSS positioning (static, relative, absolute, fixed).',
        'What is flexbox and how do you use it?',
        'Explain CSS Grid and its advantages.',
        'What are CSS media queries and responsive design?',
        'Explain CSS specificity and cascade.',
        'What is the difference between margin and padding?',
        'How do you implement CSS animations and transitions?',
        'What are CSS preprocessors like SASS and LESS?',
        'Explain CSS custom properties (variables).',
        'What is the difference between em and rem units in CSS?',
        'How do you center content in CSS?',
        'What are CSS pseudo-classes and pseudo-elements?',
        'Explain the difference between display: none and visibility: hidden.',
    ],
    'hr': [
        'Tell us about yourself.',
        'What are your strengths and weaknesses?',
        'Why do you want to work for this company?',
        'What are your career goals?',
        'Describe a challenging project you worked on and how you overcame it.',
        'How do you handle stress and pressure at work?',
        'Can you tell us about a time you worked in a team?',
        'How do you handle conflicts with team members?',
        'What is your approach to learning new technologies?',
        'Describe a time you made a mistake. How did you handle it?',
        'What is your experience with agile development?',
        'How do you prioritize tasks when working on multiple projects?',
        'Tell us about your experience with code reviews.',
        'How do you approach debugging and troubleshooting problems?',
        'What is your experience working with cross-functional teams?',
        'Describe your experience with version control systems.',
        'What do you do to stay updated with the latest technologies?',
        'How do you approach technical documentation?',
        'Tell us about your experience with testing and quality assurance.',
        'What is your approach to mentoring junior developers?',
    ],
    'project_based': [
        'Build a simple todo list application. What technologies would you use?',
        'Design a user authentication system from scratch. What are the security considerations?',
        'How would you build a real-time chat application?',
        'Design a scalable URL shortener service. How would you handle millions of requests?',
        'Build an e-commerce platform. What are the key components and databases you would use?',
        'Design a video streaming platform like YouTube. What are the architecture challenges?',
        'How would you implement a recommendation system for an online store?',
        'Design a social media feed. How would you optimize it for millions of users?',
        'Build a weather application. How would you store and retrieve weather data?',
        'Design a file sharing system like Google Drive. How would you handle storage and permissions?',
        'How would you implement a search engine for a large database?',
        'Design a payment processing system. What are the security considerations?',
        'Build a machine learning pipeline for image classification. What tools would you use?',
        'Design an analytics dashboard. How would you handle large amounts of data?',
        'Build a mobile app with offline functionality. How would you sync data when online?',
        'Design a microservices architecture for a large-scale application.',
        'How would you implement a caching strategy for a high-traffic website?',
        'Build a real-time collaborative editor like Google Docs.',
        'Design a distributed system for processing millions of events per second.',
        'How would you implement a notification system for a social media platform?',
    ]
}

# Skill keywords mapping
SKILL_KEYWORDS = {
    'python': ['python', 'py', 'django', 'flask', 'fastapi', 'numpy', 'pandas', 'machine learning'],
    'django': ['django', 'django rest', 'drf', 'rest api', 'orm'],
    'react': ['react', 'react.js', 'jsx', 'redux', 'hook', 'next.js', 'nextjs'],
    'javascript': ['javascript', 'js', 'nodejs', 'node', 'typescript', 'ts', 'express', 'npm'],
    'mongodb': ['mongodb', 'mongo', 'nosql', 'mongoose', 'firestore'],
    'sql': ['sql', 'mysql', 'postgresql', 'postgres', 'oracle', 'database', 'relational', 'sqlite'],
    'java': ['java', 'spring', 'springboot', 'maven', 'gradle', 'jvm'],
    'html_css': ['html', 'css', 'bootstrap', 'tailwind', 'scss', 'sass', 'ui/ux', 'front-end', 'frontend'],
}

def get_all_questions():
    """Get all questions from the bank."""
    all_questions = []
    for category, questions in QUESTIONS_BANK.items():
        for question_text in questions:
            all_questions.append({
                'text': question_text,
                'category': category
            })
    return all_questions

def get_questions_by_category(category):
    """Get questions by category."""
    return QUESTIONS_BANK.get(category, [])

def get_question_count():
    """Get total number of questions in the bank."""
    return sum(len(questions) for questions in QUESTIONS_BANK.values())
